repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: migrations/
        args: [ --diff, --check ]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        exclude: docs/|example-plugin/|migrations/
        args: [ ]
        additional_dependencies:
          - 'pydantic'
          - 'sqlalchemy'
          - 'fastapi'
