version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "9991:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
